# array.j = 2
# array.add(0, "a")
# array.add(1, "b")
# array.add(2, "c")
# array.add(3, "d")
# array.add(2, "e")
# array.add(2, "f")
# array.add(0, "A")
# array.remove(5)
# array.remove(2)
# print(array.a)